auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: filesystem
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_target_size: 1048576
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

scrape_configs:
  - job_name: "api_gateway"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "api_gateway"
          __path__: /var/log/api_gateway/*.log

  - job_name: "dashboard_frontend"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "dashboard_frontend"
          __path__: /var/log/dashboard/*.log

  - job_name: "chatbot"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "chatbot"
          __path__: /var/log/chatbot/*.log
